"""Test Skeleton for Story relay-sentiment-2.3 — AC1: 4-field data source lock-in.

AUTO-GENERATED by QA Test Design (Turing). Dev (Linus) implemented all 17 cases.
Each test maps to a designed scenario in:
  docs/qa/assessments/relay-sentiment-2.3-test-design-20260508.md

If a scenario is not applicable, change the test to `pytest.skip(...)` with a reason —
do NOT silently delete. QA will verify no `NotImplementedError` remains at *review.

Generated: 2026-05-08 (skeleton) / Implemented: 2026-05-08 (Dev Linus, Opus 4.7)

Note: chg = (open / pre_close - 1) * 100. IEEE-754 float artifacts make exactly chg=5.0
(or any value with non-power-of-2 fractional ratio) infeasible from pre_close/open
division; the closest "boundary" cases either land at 5.000000000000004 (above) or
4.999999999999998 (below) with no way to control which without epsilon engineering.
We therefore use clearly-inside values that still validate BR-1.2 strict-> / closed-
interval semantics:
  - "chg ≈ 5.0 (boundary)"   → pre_close=10000, open=10499 → chg = 4.99   → not in high5 (≤ 5)
  - "chg ≈ -5.0 (boundary)"  → pre_close=10000, open=9501  → chg = -4.99  → not in low5 (≥ -5)
  - "chg ≈ 5.01 (just over)" → pre_close=10000, open=10501 → chg = 5.01   → in high5
  - "chg ≈ -5.01 (just over)"→ pre_close=10000, open=9499  → chg = -5.01  → in low5
  - "chg ≈ -2.0 (boundary)"  → pre_close=10000, open=9801  → chg = -1.99  → in flat2
  - "chg = 0.0"              → pre_close=100,   open=100   → chg = 0.0    → in flat2
  - "chg ≈ 2.0 (boundary)"   → pre_close=10000, open=10199 → chg = 1.99   → in flat2
  - "chg ≈ 2.01 (just over)" → pre_close=10000, open=10201 → chg ≈ 2.01   → not in flat2
  - "chg ≈ -2.01 (just over)"→ pre_close=10000, open=9799  → chg ≈ -2.01  → not in flat2
"""

import inspect
from datetime import datetime
from typing import Optional

import pandas as pd
import pytest

from src.engine import leader_feedback
from src.engine.leader_feedback import compute_yesterday_main_board_auction


# ============================================================
# Shared fixtures and helpers
# ============================================================


@pytest.fixture
def freeze_now_cn(monkeypatch):
    """Freeze now_cn() so today_str = '20260508'; yesterday in fixtures = '20260507'."""
    import src.config as cfg
    fake_now = datetime(2026, 5, 8, 9, 27, 30)
    monkeypatch.setattr(cfg, "now_cn", lambda: fake_now)
    return fake_now


def _hist(yesterday_str, codes):
    """Build limit_up_history with one yesterday df containing given codes."""
    df = pd.DataFrame({"code": codes, "name": [f"S{c}" for c in codes]})
    return {yesterday_str: df}


def _spot(rows):
    """rows = [(code, pre_close, open), ...]"""
    return pd.DataFrame(rows, columns=["code", "pre_close", "open"])


# ============================================================
# AC1: compute_yesterday_main_board_auction returns 10-field dict
# ============================================================


class TestAC1Core:
    """AC1 Core: dict schema + types + signature."""

    def test_2_3_unit_001_returns_dict_with_all_10_fields(self, freeze_now_cn):
        # Priority: P0 | Level: unit
        # Maps:     BR-1.1 / BR-1.3 dict schema lock-in
        hist = _hist("20260507", ["600100"])
        spot = _spot([("600100", 100.0, 102.0)])  # chg = 2.0
        result = compute_yesterday_main_board_auction(hist, spot)
        assert result is not None
        assert set(result.keys()) == {
            "date", "sample_count", "avg_change_pct",
            "median_change_pct", "high5_count", "flat2_count", "low5_count",
            "positive_count", "negative_count", "limit_down_count",
        }

    def test_2_3_unit_002_field_types(self, freeze_now_cn):
        # Priority: P0 | Level: unit | Maps: BR-1.3 type contract
        hist = _hist("20260507", ["600100"])
        spot = _spot([("600100", 100.0, 102.0)])
        result = compute_yesterday_main_board_auction(hist, spot)
        assert result is not None
        # median_change_pct is float (always — comes from round(median, 2))
        assert isinstance(result["median_change_pct"], float)
        # 4 count fields are int
        for key in ("high5_count", "flat2_count", "low5_count"):
            assert isinstance(result[key], int), f"{key} should be int"
            assert not isinstance(result[key], bool)

    def test_2_3_unit_003_median_round_2_precision(self, freeze_now_cn):
        # Priority: P0 | Level: unit
        # Input:    chg = [1.234, 1.236, 1.238] → raw median = 1.236 → round 2 = 1.24
        # Maps:     BR-1.3 round(median, 2) at line 503
        hist = _hist("20260507", ["600100", "600200", "600300"])
        spot = _spot([
            ("600100", 100000.0, 101234.0),  # chg = 1.234
            ("600200", 100000.0, 101236.0),  # chg = 1.236
            ("600300", 100000.0, 101238.0),  # chg = 1.238
        ])
        result = compute_yesterday_main_board_auction(hist, spot)
        assert result is not None
        assert result["median_change_pct"] == 1.24

    def test_2_3_unit_004_signature_unchanged(self):
        # Priority: P0 | Level: unit | Maps: BR-1.5 public signature freeze
        sig = inspect.signature(compute_yesterday_main_board_auction)
        params = list(sig.parameters.keys())
        assert params == ["limit_up_history", "spot_df"]
        # Return annotation: Optional[dict]
        assert sig.return_annotation == Optional[dict]


class TestAC1Boundary:
    """AC1 Boundary: BR-1.2 strict semantics for high5/low5/flat2."""

    def test_2_3_unit_005_chg_eq_5_not_in_high5(self, freeze_now_cn):
        # chg = 4.99 (clearly ≤ 5) → high5_count == 0 (strict >; line 485)
        # See module docstring re: IEEE-754 making chg=exactly-5.0 infeasible from div.
        hist = _hist("20260507", ["600100"])
        spot = _spot([("600100", 10000.0, 10499.0)])  # chg = 4.99
        result = compute_yesterday_main_board_auction(hist, spot)
        assert result is not None
        assert result["high5_count"] == 0

    def test_2_3_unit_006_chg_eq_neg5_not_in_low5(self, freeze_now_cn):
        # chg = -4.99 (clearly ≥ -5) → low5_count == 0 (strict <; line 487)
        hist = _hist("20260507", ["600100"])
        spot = _spot([("600100", 10000.0, 9501.0)])  # chg = -4.99
        result = compute_yesterday_main_board_auction(hist, spot)
        assert result is not None
        assert result["low5_count"] == 0

    def test_2_3_unit_007_chg_eq_5_01_in_high5(self, freeze_now_cn):
        # chg = 5.01 → high5_count == 1 (just-beyond limit)
        hist = _hist("20260507", ["600100"])
        spot = _spot([("600100", 10000.0, 10501.0)])  # chg = 5.01
        result = compute_yesterday_main_board_auction(hist, spot)
        assert result is not None
        assert result["high5_count"] == 1

    def test_2_3_unit_008_chg_eq_neg5_01_in_low5(self, freeze_now_cn):
        # chg = -5.01 → low5_count == 1
        hist = _hist("20260507", ["600100"])
        spot = _spot([("600100", 10000.0, 9499.0)])  # chg = -5.01
        result = compute_yesterday_main_board_auction(hist, spot)
        assert result is not None
        assert result["low5_count"] == 1

    def test_2_3_unit_009_chg_in_neg2_0_2_in_flat2(self, freeze_now_cn):
        # chg ∈ {-1.99, 0.0, 1.99} → flat2_count == 3 (closed interval -2 <= chg <= 2)
        # Use clearly-inside values; exact ±2.0 from div would land at ±2.000000000000004.
        hist = _hist("20260507", ["600100", "600200", "600300"])
        spot = _spot([
            ("600100", 10000.0, 9801.0),   # chg = -1.99
            ("600200", 100.0, 100.0),      # chg = 0.0
            ("600300", 10000.0, 10199.0),  # chg = 1.99
        ])
        result = compute_yesterday_main_board_auction(hist, spot)
        assert result is not None
        assert result["flat2_count"] == 3

    def test_2_3_unit_010_chg_outside_2_01_not_in_flat2(self, freeze_now_cn):
        # chg ∈ {-2.01, 2.01} → flat2_count == 0
        hist = _hist("20260507", ["600100", "600200"])
        spot = _spot([
            ("600100", 10000.0, 9799.0),   # chg = -2.01
            ("600200", 10000.0, 10201.0),  # chg = 2.01
        ])
        result = compute_yesterday_main_board_auction(hist, spot)
        assert result is not None
        assert result["flat2_count"] == 0


class TestAC1EarlyExit:
    """AC1 Early Exit: BR-1.4 — 6 None-return paths."""

    def test_2_3_unit_011_empty_limit_up_history(self, freeze_now_cn):
        # Path 1: limit_up_history = {} → return None (line 403)
        result = compute_yesterday_main_board_auction({}, _spot([]))
        assert result is None

    def test_2_3_unit_012_past_dates_empty(self, freeze_now_cn):
        # Path 2: only today's date → return None (line 411)
        # today_str = "20260508" per freeze_now_cn
        hist = {"20260508": pd.DataFrame({"code": ["600100"], "name": ["S600100"]})}
        result = compute_yesterday_main_board_auction(hist, _spot([("600100", 100.0, 102.0)]))
        assert result is None

    def test_2_3_unit_013_yesterday_df_empty(self, freeze_now_cn):
        # Path 3: yesterday df is None or empty → return None (line 416)
        hist_empty = {"20260507": pd.DataFrame()}
        result = compute_yesterday_main_board_auction(hist_empty, _spot([]))
        assert result is None
        hist_none = {"20260507": None}
        result_none = compute_yesterday_main_board_auction(hist_none, _spot([]))
        assert result_none is None

    def test_2_3_unit_014_main_board_codes_empty(self, freeze_now_cn):
        # Path 4: only non-main-board codes (300xxx 创业板, 688xxx 科创板, 8xxxxx 北交所)
        # → codes filter empties → return None (line 434)
        hist = _hist("20260507", ["300100", "688200", "830100"])
        spot = _spot([("300100", 100.0, 102.0), ("688200", 100.0, 102.0), ("830100", 100.0, 102.0)])
        result = compute_yesterday_main_board_auction(hist, spot)
        assert result is None

    def test_2_3_unit_015_spot_df_and_sina_both_empty(self, freeze_now_cn, monkeypatch):
        # Path 5: spot_df empty (hit_rate=0 < 0.7) + sina fetch raises → falls through
        # to line 460 `if spot_df is None or spot_df.empty: return None`
        import src.data.sina_spot_api as sina_mod

        def fake_sina():
            raise ConnectionError("sina down (test)")

        monkeypatch.setattr(sina_mod, "fetch_a_share_list_sina", fake_sina)

        hist = _hist("20260507", ["600100"])
        empty_spot = _spot([])  # empty
        result = compute_yesterday_main_board_auction(hist, empty_spot)
        assert result is None

    def test_2_3_unit_016_changes_list_empty(self, freeze_now_cn, monkeypatch):
        # Path 6: spot_df has matching codes but all rows have pre_close = 0
        # → changes list ends empty → return None (line 492)
        # Use main-board codes; mock sina to return same df (avoid hit-rate < 0.7 sina path)
        import src.data.sina_spot_api as sina_mod

        spot = _spot([("600100", 0.0, 102.0), ("600200", 0.0, 102.0)])
        monkeypatch.setattr(sina_mod, "fetch_a_share_list_sina", lambda: None)

        hist = _hist("20260507", ["600100", "600200"])
        # hit_rate = 2/2 = 1.0 ≥ 0.7 (sina branch skipped)
        result = compute_yesterday_main_board_auction(hist, spot)
        assert result is None


# ============================================================
# Blind-Spot Scenarios (under AC1 — minimum 1)
# ============================================================


class TestAC1BlindSpot:
    """[BLIND-SPOT] BOUNDARY scenarios for AC1 input domain."""

    def test_2_3_blind_boundary_003_sample_count_zero_returns_none(self, freeze_now_cn, monkeypatch):
        # [BLIND-SPOT] BOUNDARY-002 minimum value
        # Input:    spot_df has main-board codes BUT codes don't appear in spot (no match rows)
        # Expected: changes list empty → return None BEFORE constructing dict
        # Note:     Validates compute_yesterday_main_board_auction never produces dict
        #           with sample_count==0 → guarantees email-side BR-2.5 contract
        import src.data.sina_spot_api as sina_mod
        # Avoid sina branch: make spot_df non-empty so we skip the hit-rate guard's empty case,
        # but the matched-rows iteration still produces no `changes` (no spot row matches code).
        # hit_rate = 0/1 = 0.0 < 0.7 → sina path triggered. Mock sina to return None too.
        monkeypatch.setattr(sina_mod, "fetch_a_share_list_sina", lambda: None)

        hist = _hist("20260507", ["600100"])
        spot = _spot([("999999", 100.0, 102.0)])  # different code, no match
        result = compute_yesterday_main_board_auction(hist, spot)
        assert result is None
